name: Check If Run From Tag
description: Small action to check if the source of the action is a git tag, aka a release.

runs:
  using: "composite"
 
  steps:
  - name: Display Environment
    shell: bash
    env:
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
    run: |
      echo $EVENT_CONTEXT
      
  - name: Check if run from tag
    shell: bash
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    run: |
      echo "This workflow must be run from a tag"
      exit 1
